'use strict';

// Generates workflows/procurement-triage.json. Run with `make workflow`; never edit the output.
//
// Every node starts as a copy of the node of its type in workflows/reference/node-shapes.json, an
// export from this n8n instance, so typeVersion and parameter shape come from the instance and not
// from memory. Only parameters are filled in here. Code nodes get the modules in workflows/code/ and
// the config files inlined; Postgres nodes get the statements in database/queries/ verbatim.
// Credentials are referenced by name and never carry secrets.

const crypto = require('node:crypto');
const fs = require('node:fs');
const path = require('node:path');

const ROOT = path.resolve(__dirname, '..');
const OUTPUT = 'workflows/procurement-triage.json';
const MAPLEPROCURE = 'https://maple-procure.onrender.com';
const ANTHROPIC = 'https://api.anthropic.com/v1/messages';
// `id: null` makes n8n resolve each credential by name and type on import. Without it, n8n falls
// back to a credential of the same type, which bound the Anthropic call to the MapleProcure token.
const CREDENTIALS = {
  postgres: { postgres: { id: null, name: 'Postgres triage' } },
  mapleprocure: { httpHeaderAuth: { id: null, name: 'MapleProcure API' } },
  anthropic: { httpHeaderAuth: { id: null, name: 'Anthropic API' } },
};
const RETRY = { retryOnFail: true, maxTries: 3, waitBetweenTries: 5000 };

const inputs = [];
function read(file) {
  const text = fs.readFileSync(path.join(ROOT, file), 'utf8');
  inputs.push(file, text);
  return text;
}
const readJson = (file) => JSON.parse(read(file));

const reference = readJson('workflows/reference/node-shapes.json');
const profile = readJson('config/search-profile.json');
const rules = readJson('config/routing-rules.json');
const settings = readJson('config/classifier.json');
const prompt = read('config/classifier-prompt.md');

function hash(text) {
  return crypto.createHash('sha256').update(text).digest('hex');
}

function stableId(name) {
  const h = hash(`mapleprocure-triage/${name}`);
  return `${h.slice(0, 8)}-${h.slice(8, 12)}-4${h.slice(13, 16)}-8${h.slice(17, 20)}-${h.slice(20, 32)}`;
}

function isObject(value) {
  return typeof value === 'object' && value !== null && !Array.isArray(value);
}

function merge(base, over) {
  const out = { ...base };
  for (const [key, value] of Object.entries(over)) {
    out[key] = isObject(value) && isObject(base[key]) ? merge(base[key], value) : value;
  }
  return out;
}

function node(type, name, parameters, extra = {}, referenceName = null) {
  const shape = reference.nodes.find((candidate) => candidate.type === type &&
    (referenceName === null || candidate.name === referenceName));
  if (!shape) {
    throw new Error(`${type} is not in node-shapes.json: export it from the instance first`);
  }
  return {
    parameters: merge(structuredClone(shape.parameters), parameters),
    type: shape.type,
    typeVersion: shape.typeVersion,
    position: [0, 0],
    id: stableId(name),
    name,
    ...extra,
  };
}

function inlineModule(file) {
  const source = read(`workflows/code/${file}`);
  const exported = /module\.exports = \{([^}]*)\};/.exec(source);
  if (!exported) {
    throw new Error(`${file} has no module.exports object`);
  }
  const names = exported[1].split(',').map((name) => name.trim()).filter(Boolean);
  return `const { ${names.join(', ')} } = (() => {\nconst module = { exports: {} };\n` +
    `${source}\nreturn module.exports;\n})();`;
}

function code(name, mode, { modules = [], constants = {}, body }) {
  const parts = [
    `// Generated by workflows/build.js. Module source is copied from workflows/code/: edit there.`,
    ...Object.entries(constants).map(([key, value]) => `const ${key} = ${JSON.stringify(value, null, 2)};`),
    ...modules.map(inlineModule),
    body.trim(),
  ];
  return node('n8n-nodes-base.code', name, { mode, jsCode: parts.join('\n\n') });
}

// jsonb parameters are passed as JSON text. The Postgres node sends an array value as a Postgres
// array literal, which cannot be cast to jsonb (the first live run failed on exactly that).
function sql(name, file, queryReplacement, extra = {}, options = {}) {
  return node('n8n-nodes-base.postgres', name, {
    operation: 'executeQuery',
    query: read(`database/queries/${file}`),
    options: { queryReplacement, ...options },
  }, { credentials: CREDENTIALS.postgres, ...extra }, 'Execute a SQL query');
}

function http(name, parameters, credentials, extra = {}) {
  return node('n8n-nodes-base.httpRequest', name, parameters, { credentials, ...RETRY, ...extra });
}

const version = hash(fs.readFileSync(__filename, 'utf8') + JSON.stringify(profile) +
  JSON.stringify(rules) + JSON.stringify(settings) + prompt +
  fs.readdirSync(path.join(ROOT, 'workflows/code')).filter((f) => f.endsWith('.js')).sort()
    .map((f) => fs.readFileSync(path.join(ROOT, 'workflows/code', f), 'utf8')).join('') +
  fs.readdirSync(path.join(ROOT, 'database/queries')).sort()
    .map((f) => fs.readFileSync(path.join(ROOT, 'database/queries', f), 'utf8')).join('')).slice(0, 12);

const nodes = [
  node('n8n-nodes-base.scheduleTrigger', 'Every hour', {}),
  node('n8n-nodes-base.manualTrigger', 'Run now', {}),
  sql('Recover stale claims', 'recover.sql', '={{ [ $execution.id ] }}', { alwaysOutputData: true }),
  code('Build search requests', 'runOnceForAllItems', {
    modules: ['build-requests.js'],
    constants: { profile },
    body: 'return buildRequests(profile).map((request) => ({ json: request }));',
  }),
  http('Search MapleProcure', {
    url: `={{ '${MAPLEPROCURE}' + $json.path }}`,
    sendQuery: true,
    specifyQuery: 'json',
    jsonQuery: '={{ JSON.stringify($json.query) }}',
    options: { batching: { batch: { batchSize: 4, batchInterval: 250 } }, timeout: 120000 },
  }, CREDENTIALS.mapleprocure),
  code('Merge search results', 'runOnceForAllItems', {
    modules: ['merge-results.js'],
    body: `
const requests = $('Build search requests').all();
const responses = $input.all().map((item, index) => {
  const paired = Array.isArray(item.pairedItem) ? item.pairedItem[0] : item.pairedItem;
  return { concept: requests[paired ? paired.item : index].json.concept, body: item.json };
});
const now = $now.setZone('America/Toronto').toFormat("yyyy-MM-dd'T'HH:mm:ss");
return [{ json: mergeResults(responses, { now }) }];`,
  }),
  sql('Claim notices', 'claim.sql',
    `={{ [ JSON.stringify($json.notices), $execution.id, '${version}' ] }}`,
    { alwaysOutputData: true }),
  code('Collect work', 'runOnceForAllItems', {
    body: `
const claimed = $input.all().map((item) => item.json)
  .filter((row) => typeof row.tender_reference === 'string');
const recovered = $('Recover stale claims').all().map((item) => item.json)
  .filter((row) => row.status === 'PENDING');
return [...recovered, ...claimed].map((row) => ({ json: { tender_reference: row.tender_reference } }));`,
  }),
  http('Fetch notice', {
    url: `={{ '${MAPLEPROCURE}/v1/tenders/' + encodeURIComponent($json.tender_reference) }}`,
    options: { batching: { batch: { batchSize: 5, batchInterval: 200 } }, timeout: 120000 },
  }, CREDENTIALS.mapleprocure, { onError: 'continueRegularOutput' }),
  code('Prepare classification', 'runOnceForEachItem', {
    modules: ['prepare-classification.js'],
    constants: { settings, prompt, contract: rules.contract },
    body: `
const reference = $('Collect work').item.json.tender_reference;
return { json: prepareClassification($json, reference, { settings, prompt, contract }) };`,
  }),
  node('n8n-nodes-base.if', 'Notice found?', {
    conditions: {
      conditions: [{
        id: stableId('Notice found? condition'),
        leftValue: '={{ String($json.found) }}',
        rightValue: 'true',
        operator: { type: 'string', operation: 'equals', name: 'filter.operator.equals' },
      }],
    },
  }),
  http('Classify', {
    method: 'POST',
    url: ANTHROPIC,
    sendHeaders: true,
    headerParameters: { parameters: [
      { name: 'anthropic-version', value: '2023-06-01' },
      { name: 'anthropic-beta', value: settings.beta },
    ] },
    sendBody: true,
    specifyBody: 'json',
    jsonBody: '={{ JSON.stringify($json.request) }}',
    options: { batching: { batch: { batchSize: 5, batchInterval: 500 } }, timeout: 300000 },
  }, CREDENTIALS.anthropic, { onError: 'continueRegularOutput' }),
  code('Validate and route', 'runOnceForAllItems', {
    modules: ['validate-classification.js', 'route.js', 'classification-record.js'],
    constants: { rules, promptVersion: settings.version },
    body: `
const records = [];
$input.all().forEach((item, index) => {
  const prepared = $('Prepare classification').itemMatching(index).json;
  const record = recordFor(item.json, prepared, { rules, promptVersion },
    { validateClassification, route });
  if (record !== null) {
    records.push({ json: { tender_reference: prepared.tender_reference, record },
      pairedItem: { item: index } });
  }
});
return records;`,
  }),
  sql('Record classification', 'record-classification.sql',
    '={{ [ $json.tender_reference, $execution.id, JSON.stringify($json.record) ] }}', {},
    { queryBatching: 'independently' }),
];

const path_ = [
  'Recover stale claims', 'Build search requests', 'Search MapleProcure', 'Merge search results',
  'Claim notices', 'Collect work', 'Fetch notice', 'Prepare classification', 'Notice found?',
  'Classify', 'Validate and route', 'Record classification',
];
const connections = {};
const link = (from, to) => ({ main: [[{ node: to, type: 'main', index: 0 }]] });
connections['Every hour'] = link('Every hour', path_[0]);
connections['Run now'] = link('Run now', path_[0]);
path_.slice(0, -1).forEach((from, i) => { connections[from] = link(from, path_[i + 1]); });
connections['Notice found?'].main.push([]);

const positions = { 'Every hour': [0, 0], 'Run now': [0, 192] };
path_.forEach((name, i) => { positions[name] = [224 * (i + 1), 96]; });
for (const n of nodes) {
  n.position = positions[n.name];
}

const workflow = {
  id: 'mapleProcureTriage',
  name: 'MapleProcure triage',
  active: false,
  nodes,
  connections,
  settings: reference.settings,
  pinData: {},
  tags: [],
};
fs.writeFileSync(path.join(ROOT, OUTPUT), `${JSON.stringify(workflow, null, 2)}\n`);
console.log(`wrote ${OUTPUT}: ${nodes.length} nodes, workflow version ${version}`);
